name: dart_obfuscator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
#  sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
#  path: 1.7.0
  path: ^1.8.2

dev_dependencies:
  test: ^1.15.4
